### ISSUE TITLE
Error when revoking token via RevokeOAuth2Token method

### ISSUE THREAD

**Issue by patzj** [ory/hydra-client-go#22]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra-client-go/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra-client-go/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When I'm using the SDK to revoke a token, I'm getting .

### Reproducing the bug

1. Create an Echo endpoint to revoke a token:

```go
func RevokeTokenHandler(c echo.Context) error {
        // ... code snippet

	_, err := apiClient.OAuth2API.
		RevokeOAuth2Token(requestCtx).
		ClientSecret(payload.ClientSecret).
		ClientId(payload.ClientId).
		Token(payload.Token).
		Execute()

	if err != nil {
		fmt.Println(err.Error())
		return err
	}

	return nil
}
```

2. Send POST request to the endpoint with JSON data:

```json
{
	"clientId": "<reducted>",
	"clientSecret": "<reducted>",
	"token": "ory_at_<reducted>"
}
```

### Relevant log output

```shell
{"time":"2024-03-04T15:49:36.170649869+08:00","id":"","remote_ip":"::1","host":"localhost:8080","method":"POST","uri":"/au/auth/token/revoke","user_agent":"insomnia/2023.5.8","status":500,"error":"json: cannot unmarshal object into Go struct field _ErrorOAuth2.error of type string","latency":2573077,"latency_human":"2.573077ms","bytes_in":211,"bytes_out":36}
```

### Relevant configuration

```yml
services:
  hydra:
    image: oryd/hydra:v2.2.0
    container_name: hydra
    ports:
      - 5444:4444
      - 5445:4445
      - 5555:5555
    environment:
      - SECRETS_SYSTEM=grantwardishydra
      - URLS_SELF_ISSUER=http://localhost:4444
      - URLS_LOGIN=http://localhost:9020/login
      - URLS_LOGOUT=http://localhost:9020/logout
      - URLS_CONSENT=http://localhost:9020/consent
      - DSN=postgres://hydra:secret@postgres:5432/hydra?sslmode=disable
    command: serve all --dev
    restart: unless-stopped
    depends_on:
      - postgres
      - hydra-migrate
    networks:
      - backend

  hydra-migrate:
    image: oryd/hydra:v2.2.0
    container_name: hydra-migrate
    environment:
      - DSN=postgres://hydra:secret@postgres:5432/hydra?sslmode=disable
    command: migrate sql -e --yes
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - backend

  hydra-consent:
    image: oryd/hydra-login-consent-node:v2.2.0
    container_name: hydra-consent
    ports:
      - 9020:3000
    environment:
      - HYDRA_ADMIN_URL=http://hydra:4445
    restart: unless-stopped
    networks:
      - backend

  postgres:
    image: postgres
    container_name: hydra-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=hydra
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
    networks:
      - backend

networks:
  backend:
    name: hydra-net
```

### Version

v2.2.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker
